I="single game inventory icon, one chunky object centred, thick bold black outline, one clear readable silhouette, transparent background"
S={
'ash_glass':"a jagged shard of smoky grey-black volcanic ash glass with a pale blue glint",
'bandage':"a rolled cream-coloured cloth field bandage with a red cross on it and a loose tail",
'bog_iron':"a heavy lumpy chunk of rusty orange-brown bog iron ore with dark pits",
'brew_fire':"a brown swing-top beer bottle filled with glowing orange fire beer, small flames licking from the top",
'brew_water':"a brown swing-top beer bottle filled with bright blue water beer, a little splash of water at the top",
'brew_keeper':"a brown swing-top beer bottle filled with green herbal tonic, a yellow goalkeeper glove tied to its neck",
'coins':"a short stack of shiny gold coins with one coin leaning against it",
'deep_salts':"a chunk of deep blue-violet salt crystal with sharp facets",
'key':"an old brass key with a round ring bow and a big toothed bit",
'orange':"a round orange fruit with one green leaf on the stem",
'reed':"a bundle of three marsh reeds with brown cattail heads tied with string",
'salts':"a small corked glass vial of white smelling salt crystals with a red label",
'scroll':"a rolled parchment recipe scroll tied with a red ribbon",
'stone':"a fist-sized round grey throwing stone",
'trait_fire':"a single orange and yellow flame",
'trait_fire_1':"a bigger orange and yellow flame with flying sparks",
'trait_fire_2':"a roaring orange and yellow fire on crossed logs with sparks",
'trait_fire_3':"a huge blazing orange fireball burst with a bright yellow core and a ring of sparks",
'trait_lorelei':"the head of a river siren girl with long flowing red hair",
'trait_lorelei_1':"the head of a river siren girl with long flowing red hair and a golden comb in it, a teal wave below",
'trait_lorelei_2':"the head of a river siren girl with long flowing red hair, singing, golden comb, musical notes and a teal wave around her",
'trait_normal':"a plain brown leather football",
'trait_normal_1':"a brown leather football tied on a wanderer's bindle stick",
'trait_normal_2':"a brown leather football inside a golden laurel wreath",
'trait_star':"one bold yellow star",
'trait_star_1':"two bold yellow stars side by side",
'trait_star_2':"three bold yellow stars over a small golden crown",
'trait_wand':"a purple magic wand with a white star at the tip",
'trait_wand_1':"a purple magic wand with a white star at the tip and a burst of sparkles",
'trait_wand_2':"an ornate golden and purple magic wand with a big glowing star tip and many sparkles",
'trait_water':"a single blue water drop",
'trait_water_1':"a big blue water drop with a small splash at its base",
'trait_water_2':"a blue water splash crown with flying droplets",
'trait_water_3':"a big curling blue ocean wave with white foam",
}
