I="game icon, centred, nothing else in the picture, thick bold black outline, one clear readable silhouette, transparent background"
S2={
'salts':"a small corked glass vial of white smelling salt crystals with a red label",
'brew_fire':"an upright brown swing-top beer bottle filled with glowing orange fire beer, small flames rising from its open top",
'stone':"a smooth round grey river stone",
'trait_fire':"a single orange and yellow flame",
'trait_fire_1':"a tall orange and yellow flame with three flying sparks",
'trait_fire_2':"a roaring orange and yellow fire burning on two crossed wooden logs",
'trait_fire_3':"a huge blazing orange fireball burst with a bright yellow core and a ring of sparks",
'trait_rivals':"two angry cartoon faces in profile glaring nose to nose, one purple one grey",
'trait_rivals_1':"two angry cartoon faces in profile glaring nose to nose, one purple one grey, red anger marks and sweat drops",
'trait_rivals_2':"two furious cartoon faces in profile shouting nose to nose, one purple one grey, a yellow lightning bolt between them and a gold ring around them",
'trait_star':"one big bold five-pointed yellow star",
'trait_star_1':"two big bold five-pointed yellow stars overlapping",
'trait_star_2':"three bold five-pointed yellow stars in an arc above a small golden crown",
'trait_wand':"a purple magic wand with a pale yellow star at the tip",
'trait_wand_1':"a purple magic wand with a pale yellow star at the tip and a burst of yellow sparkles",
'trait_water':"a single blue water drop",
'trait_water_1':"a big blue water drop with a small splash at its base",
'trait_water_2':"a blue water splash crown with flying droplets",
'trait_water_3':"a big curling blue ocean wave with pale foam",
'trait_normal':"a round black and white soccer ball",
'trait_normal_1':"a round black and white soccer ball tied in a red cloth bundle on a wanderer's stick",
'trait_normal_2':"a round black and white soccer ball inside a golden laurel wreath",
}
